name: Publish Python distributions to PyPI and TestPyPI

on: [push]

jobs:
  build:
    name: Build and publish Python distribution
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Initialize Python 3.9
      uses: actions/setup-python@v2
    with:
        python-version: '3.9'
        cache: 'pip'
    - name: Install dependencies
        run: |
        python -m pip install --upgrade pip
        if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            
