name: Python Pull Request Workflow
on: push
jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Run unit tests
        run: |
          pip install -r requirements.txt